services:
  - type: web
    name: aviders-backend-spin
    env: node
    rootDir: AVIDERS_BACKEND_Spin-main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
